src/railway_ticket_booksystem/booksystem/urls.py
from django.conf.urls import url
from . import views

app_name = 'booksystem'  # 添加这个属性，方便jinja语法

urlpatterns = [
    # 注册与登录
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^login_user/$', views.login_user, name='login_user'),  # 登入
    url(r'^logout_user/$', views.logout_user, name='logout_user'),  # 登出

    # 主要页面
    url(r'^$', views.index, name='index'),  # 欢迎页面
    url(r'^result/$', views.result, name='result'),  # 搜索结果
    url(r'^user_info/$', views.user_info, name='user_info'),  # 用户信息
    url(r'^book/railway/(?P<railway_id>[0-9]+)/$', views.book_ticket, name='book_ticket'),  # 订票
    url(r'^refund/railway/(?P<railway_id>[0-9]+)/$', views.refund_ticket, name='refund_ticket'),  # 退票
]

src/railway_ticket_booksystem/railway_ticket_booksystem/urls.py
# -*- coding: UTF-8 -*-  
from django.conf.urls import url, include
from django.contrib import admin
from booksystem import views

urlpatterns = [
    url(r'^booksystem/admin/', include(admin.site.urls)),
    url(r'^booksystem/admin/finance', views.admin_finance, name='admin_finance'),  
    url(r'^booksystem/', include('booksystem.urls')),
    url(r'', include('booksystem.urls')),
]

src/railway_ticket_booksystem/booksystem/models.py
# Create your models here.
# -*- coding: UTF-8 -*-  
from django.contrib.auth.models import Permission, User
from django.db import models


# Create your models here.

class railway(models.Model):
    user = models.ManyToManyField(User, default=1)  # 有了这个字段之后，默认的后台添加失效，必须要自定义Form，除去这个字段
    name = models.CharField(max_length=100)  # 班次
    leave_city = models.CharField(max_length=100, null=True)  # 离开城市
    arrive_city = models.CharField(max_length=100, null=True)  # 到达城市
    leave_station = models.CharField(max_length=100, null=True)  # 离开的车站
    arrive_station = models.CharField(max_length=100, null=True)  # 到达的车站
    leave_time = models.DateTimeField(null=True)  # DateTimeField包括了DateField信息，并且添加了时间
    arrive_time = models.DateTimeField(null=True)
    capacity = models.IntegerField(default=0, null=True)  # 座位总数
    price = models.FloatField(default=0, null=True)  # 价格
    book_sum = models.IntegerField(default=0, null=True)  # 订票总人数
    income = models.FloatField(default=0, null=True)  # 收入

    def __str__(self):
        return self.name

src/railway_ticket_booksystem/booksystem/forms.py
# -*- coding: UTF-8 -*-  
from django import forms
from django.contrib.auth.models import User
from .models import railway


class PassengerInfoForm(forms.Form):
    leave_city = forms.CharField(label='leave_city', max_length=100)
    arrive_city = forms.CharField(label='arrive_city', max_length=100)
    leave_date = forms.DateField(label='leave_date')


# 自定义railway对象的输入信息
class railwayForm(forms.ModelForm):
    class Meta:
        model = railway
        exclude = ['user']  # user信息不能从后台输入


# 用户需要输入的字段
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

src/railway_ticket_booksystem/booksystem/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from .forms import PassengerInfoForm, UserForm
from .models import railway as Railway
from .classes import IncomeMetric, Order
from django.contrib.auth.models import Permission, User
import datetime, pytz
from operator import attrgetter

ADMIN_ID = 1


# 管理员后台财务管理
# 统计航空公司每周、每月，每年营业收入情况。
def admin_finance(request):
    global Railway
    all_railways = Railway.objects.all()
    all_railways = sorted(all_railways, key=attrgetter('leave_time'))  # 将所有车次按照出发时间排序

    # 将车次每天的输入打上不同的时间标签 [周，月，日]
    week_day_incomes = []
    month_day_incomes = []
    year_day_incomes = []

    # 用set存储所有的 周，月，年
    week_set = set()
    month_set = set()
    year_set = set()
    for railway in all_railways:
        if railway.income > 0:  # 只统计有收入的车次
            # 打上周标签
            this_week = railway.leave_time.strftime('%W')  # datetime获取周
            week_day_incomes.append((this_week, railway.income))  # 添加元组(week, income)
            week_set.add(this_week)
            # 打上月标签
            this_month = railway.leave_time.strftime('%m')  # datetime获取月
            month_day_incomes.append((this_month, railway.income))  # 添加元组(month, income)
            month_set.add(this_month)
            # 打上年标签
            this_year = railway.leave_time.strftime('%Y')  # datetime获取年
            year_day_incomes.append((this_year, railway.income))  # 添加元组(year, income)
            year_set.add(this_year)

    # 存储每周收入
    # 将每周的收入用 IncomeMetric 类型存储在 week_incomes List中
    week_incomes = []
    for week in week_set:
        income = sum(x[1] for x in week_day_incomes if x[0] == week)  # 同周次的income求和
        railway_sum = sum(1 for x in week_day_incomes if x[0] == week)  # 同周次的车次总数目
        week_income = IncomeMetric(week, railway_sum, income)  # 将数据存储到IncomeMetric类中，方便jinja语法
        week_incomes.append(week_income)
    week_incomes = sorted(week_incomes, key=attrgetter('metric'))  # 将List类型的 week_incomes 按周次升序排列

    # 存储每月收入
    # 将每月的收入用 IncomeMetric 类型存储在 month_incomes List中
    month_incomes = []
    for month in month_set:
        income = sum(x[1] for x in month_day_incomes if x[0] == month)
        railway_sum = sum(1 for x in month_day_incomes if x[0] == month)
        month_income = IncomeMetric(month, railway_sum, income)
        month_incomes.append(month_income)
    month_incomes = sorted(month_incomes, key=attrgetter('metric'))  # 将List类型的 month_incomes 按月份升序排列

    # 存储每年收入
    # 将每年的收入用 IncomeMetric 类型存储在 year_incomes List中
    year_incomes = []
    for year in year_set:
        income = sum(x[1] for x in year_day_incomes if x[0] == year)
        railway_sum = sum(1 for x in year_day_incomes if x[0] == year)
        year_income = IncomeMetric(year, railway_sum, income)
        year_incomes.append(year_income)
    year_incomes = sorted(year_incomes, key=attrgetter('metric'))  # 将List类型的 year_incomes 按年份升序排列

    # 存储order信息
    passengers = User.objects.exclude(pk=1)  # 去掉管理员
    order_set = set()
    for p in passengers:
        railways = Railway.objects.filter(user=p)
        for f in railways:
            route = f.leave_city + ' → ' + f.arrive_city
            order = Order(p.username, f.name, route, f.leave_time, f.price)
            order_set.add(order)

    # 信息传给前端
    context = {
        'week_incomes': week_incomes,
        'month_incomes': month_incomes,
        'year_incomes': year_incomes,
        'order_set': order_set
    }
    print(context)
    return context


# 显示用户订单信息
# 车次信息，退票管理
def user_info(request):
    global railway
    if request.user.is_authenticated():
        # 如果用户是管理员，render公司车次收入统计信息页面 admin_finance
        print(request.user.id)
        if request.user.id == ADMIN_ID:
            context = admin_finance(request)  # 获取要传入前端的数据
            return render(request, 'booksystem/admin_finance.html', context)
        # 如果用户是普通用户，render用户的机票信息 user_info
        else:
            booked_railways = Railway.objects.filter(user=request.user)  # 从 booksystem_railway_user 表过滤出该用户订的车次
            context = {
                'booked_railways': booked_railways,
                'username': request.user.username,  # 导航栏信息更新
            }
            return render(request, 'booksystem/user_info.html', context)
    return render(request, 'booksystem/login.html')  # 用户如果没登录，render登录页面


# 主页
# 欢迎页面性质的订票页面
def index(request):
    return render(request, 'booksystem/index.html')


# 免除csrf
@csrf_exempt
def book_ticket(request, railway_id):
    if not request.user.is_authenticated():  # 如果没登录就render登录页面
        return render(request, 'booksystem/login.html')
    else:
        global Railway
        railway = Railway.objects.get(pk=railway_id)
        # 查看乘客已经订购的railways
        booked_railways = Railway.objects.filter(user=request.user)  # 返回 QuerySet

        if railway in booked_railways:
            return render(request, 'booksystem/book_conflict.html')

        # book_railway.html 点确认之后，request为 POST 方法，虽然没有传递什么值，但是传递了 POST 信号
        # 确认订票，railway数据库改变

        # 验证一下，同样的机票只能订一次
        if request.method == 'POST':
            if railway.capacity > 0:
                railway.book_sum += 1
                railway.capacity -= 1
                railway.income += railway.price
                railway.user.add(request.user)
                railway.save()  # 一定要记着save
        # 传递更改之后的票务信息
        context = {
            'railway': railway,
            'username': request.user.username
        }
        return render(request, 'booksystem/book_railway.html', context)


# 退票
def refund_ticket(request, railway_id):
    global Railway
    railway = Railway.objects.get(pk=railway_id)
    railway.book_sum -= 1
    railway.capacity += 1
    railway.income -= railway.price
    railway.user.remove(request.user)
    railway.save()
    return HttpResponseRedirect('/booksystem/user_info')


# 退出登录
def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'booksystem/login.html', context)


# 登录
def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        user = authenticate(username=username, password=password)
        if user is not None:  # 登录成功
            if user.is_active:  # 加载订票页面
                login(request, user)
                context = {
                    'username': request.user.username
                }
                if user.id == ADMIN_ID:
                    context = admin_finance(request)  # 获取要传入前端的数据
                    return render(request, 'booksystem/admin_finance.html', context)
                else:
                    return render(request, 'booksystem/result.html', context)
            else:
                return render(request, 'booksystem/login.html', {'error_message': 'Your account has been disabled'})
        else:  # 登录失败
            return render(request, 'booksystem/login.html', {'error_message': 'Invalid login'})
    return render(request, 'booksystem/login.html')


# 注册
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                context = {
                    'username': request.user.username
                }
                return render(request, 'booksystem/result.html', context)  # 注册成功直接render result页面
    context = {
        "form": form,
    }
    return render(request, 'booksystem/register.html', context)


# 搜索结果页面
def result(request):
    if request.method == 'POST':
        form = PassengerInfoForm(request.POST)  # 绑定数据至表单
        if form.is_valid():
            passenger_lcity = form.cleaned_data.get('leave_city')
            passenger_acity = form.cleaned_data.get('arrive_city')
            passenger_ldate = form.cleaned_data.get('leave_date')
            # print(type(passenger_ldate))

            # 全设为naive比较
            # china_tz = pytz.timezone('Asia/Shanghai')
            # passenger_ltime = datetime.datetime(
            #     year=passenger_ldate.year,
            #     month=passenger_ldate.month,
            #     day=passenger_ldate.day,
            #     hour=0, minute=0, second=0,
            #     tzinfo=china_tz
            # )

            # 全设为aware比较
            passenger_ltime = datetime.datetime.combine(passenger_ldate, datetime.time())
            print(passenger_ltime)

            # filter 可用车次
            global Railway
            all_railways = Railway.objects.filter(leave_city=passenger_lcity, arrive_city=passenger_acity)
            usable_railways = []
            for railway in all_railways:  # off-set aware
                railway.leave_time = railway.leave_time.replace(tzinfo=None)  # replace方法必须要赋值。。笑哭
                if railway.leave_time.date() == passenger_ltime.date():  # 只查找当天的车次
                    usable_railways.append(railway)

            # 按不同的key排序
            usable_railways_by_ltime = sorted(usable_railways, key=attrgetter('leave_time'))  # 出发时间从早到晚
            usable_railways_by_atime = sorted(usable_railways, key=attrgetter('arrive_time'))
            usable_railways_by_price = sorted(usable_railways, key=attrgetter('price'))  # 价格从低到高

            # 转换时间格式
            time_format = '%H:%M'
            # for railway in usable_railways_by_ltime:
            #     railway.leave_time = railway.leave_time.strftime(time_format)  # 转成了str
            #     railway.arrive_time = railway.arrive_time.strftime(time_format)
            #

src/railway_ticket_booksystem/booksystem/templates/booksystem/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>火车票管理系统</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {#    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">#}
    {% block style %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body style="background-color: #f1f1f1">
<nav class="nav navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'booksystem:index' %}">GZY Railway</a>
        </div>
        <!-- Items -->
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'booksystem:result' %}">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; 购票
                </a>
            </li>
            <li>
                <a href="{% url 'booksystem:user_info' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 个人中心
                </a>
            </li>
            <li>
                {% block login_display %} <!--在用户登录之后改变这一块的显示内容-->
                    <a href="{% url 'booksystem:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; 登录
                    </a>
                {% endblock %}
            </li>
            <li>
                <a href="{% url 'booksystem:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; 退出
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

src/railway_ticket_booksystem/booksystem/templates/booksystem/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-6" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-6">{{ field }}</div>
    </div>
{% endfor %}

src/railway_ticket_booksystem/booksystem/templates/booksystem/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>火车票预订系统</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% load staticfiles %}
    <style>
        body {
            /*background: url("../../static/img/flight-bg.jpg");*/
            background: url("{% static 'img/railway.jpg' %}");
            background-size: cover; /*自适应浏览器*/
        }
    </style>

</head>
<body>

<!--导航条适应背景色-->
{#<nav class="navbar nav-divider">#}
{#    <div class="container-fluid" style="margin-top: 10px">#}
{#        <div class="navbar-header">#}
{#            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 50px;">CSU Airlines</a>#}
{#        </div>#}
{#        <div class="navbar-right">#}
{#            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 24px;">LOG IN</a>#}
{#        </div>#}
{##}
{#    </div>#}
{#</nav>#}

<div class="container-fluid" style="position:absolute;margin-top:10%;width: 35%;left: 55%">
    <h1 style="color: white">Where would you go ?</h1>
    <br>
    <form class="form-horizontal" role="form" action="{% url 'booksystem:result' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="leave_city" class="input-group-addon">出发城市</label>   <!--input必须要指定name-->
            <input id="leave_city" type="text" name="leave_city" class="form-control" placeholder="City">
        </div>
        <br>
        <div class="input-group">
            <label for="arrive_city" class="input-group-addon">到达城市</label>
            <input id="arrive_city" type="text" name="arrive_city" class="form-control" placeholder="City">
        </div>
        <br>
        <div class="input-group">
            <label for="leave_date" class="input-group-addon">出发日期</label>
            <input id="leave_date" type="date" name="leave_date" class="form-control" placeholder="Date">
        </div>
        <br>
        <center>
            <button type="submit" class="btn btn-success">Let's Go</button>
        </center>
    </form>
</div>

</body>
</html>

src/railway_ticket_booksystem/booksystem/templates/booksystem/login.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>登录账号</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="{% url 'booksystem:login_user' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_username" maxlength="10" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_password" maxlength="10" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Don't have an account? <a href="{% url 'booksystem:register' %}">Click here</a> to register.
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/railway_ticket_booksystem/booksystem/templates/booksystem/result.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} 先生/女士</a>
{% endblock %}

{#这部分在base.html的head部分才会先加载#}
{% block style %}

    <style>

        .main {
            margin-left: 50px;
            margin-right: 50px;
        }

        .search_form {
            background-color: white;
            margin-top: 25px;
            height: 90px;
        }

        .search_head {
            background-color: #f1f1f1;
            margin-top: 10px;
            height: 30px;
            text-align: center;
            font-weight: bold;
        }

        .search_result_by_ltime { /*背景色与网页背景色相同*/
            background-color: #f1f1f1;
            margin-top: 10px;
        }

        .search_result_by_price { /*背景色与网页背景色相同*/
            background-color: #f1f1f1;
            margin-top: 10px;
        }

        .one_line {
            background-color: white;
            height: 90px;
            margin-top: 10px;
            text-align: center;
        }

        .ico_search_type {
            display: inline-block; /*同行显示*/
            width: 20px;
            height: 20px;
            background: url('http://pic.c-ctrip.com/railway/searchlist/icon_search_select.png') no-repeat;
        }

        .ico_search_lcity {
            background-position: 0 0;
        }

        .ico_search_acity {
            background-position: 0 -20px;
        }

        .ico_search_ldate {
            background-position: 0 -40px;
        }

        .my_input {
            position: absolute;
            width: 80%;
        }

        .btn-warning {
            background-color: #ffb000;
        }

        .railway_name {
            line-height: 90px;
            font-size: x-large;
            font-weight: bold;
        }


    </style>
{% endblock %}

{% block js %}
    <script>
        function search_by_ltime() {
            document.getElementById("result_by_ltime").style.display = "block";
            document.getElementById("result_by_atime").style.display = "none";
            document.getElementById("result_by_price").style.display = "none";
        }
        function search_by_atime() {
            document.getElementById("result_by_ltime").style.display = "none";
            document.getElementById("result_by_atime").style.display = "block";
            document.getElementById("result_by_price").style.display = "none";
        }
        function search_by_price() {
            document.getElementById("result_by_ltime").style.display = "none";
            document.getElementById("result_by_atime").style.display = "none";
            document.getElementById("result_by_price").style.display = "block";
        }
    </script>
{% endblock %}

{% block content %}

    <div class="main">

        <!--搜索框-->
        <div class="search_form">
            <div class="col-sm-12" style="margin-top: 20px">
                <form action="{% url 'booksystem:result' %}" method="post">
                    {% csrf_token %}
                    <div class="col-sm-3"> {# 在父div中要指定width:100%才会一样宽 #}
                        <span class="ico_search_type ico_search_lcity"></span><br>
                        <input class="my_input" type="text" id="leave_city" name="leave_city" placeholder="City"
                               value="{{ leave_city }}">
                    </div>
                    <div class="col-sm-3">
                        <span class="ico_search_type ico_search_acity"></span><br>
                        <input class="my_input" type="text" id="arrive_city" name="arrive_city" placeholder="City"
                               value="{{ arrive_city }}">
                    </div>
                    <div class="col-sm-3">
                        <span class="ico_search_type ico_search_ldate"></span><br>
                        <input class="my_input" type="date" id="leave_date" name="leave_date" placeholder="Date"
                               value="{{ leave_date }}">
                    </div>
                    <div class="col-sm-3">
                        <div style="position: absolute;margin-top: 10px;margin-left: 35%">
                            <input class="btn btn btn-info" name="research_btn" type="submit" value="重新搜索">
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <!--标题行(标明4种排序方式)-->
        <div class="search_head" id="search_head" style="display: {{ dis_search_head }}">
            <div class="col-sm-12">
                <button class="col-sm-3 btn btn-primary">车次信息</button>
                <button class="col-sm-3 btn btn-success" onclick="search_by_ltime()">出发时间</button>
                <button class="col-sm-3 btn btn-danger" onclick="search_by_atime()">到达时间</button>
                <button class="col-sm-3 btn btn-warning" onclick="search_by_price()">价格</button>
            </div>
        </div>

        <!--如果没有查找到-->
        <div class="alert" id="search_failure"
             style="margin-top: 20px; background-color:white;display: {{ dis_search_failure }}">
            <h1>尊敬的旅客</h1>
            <p style="margin-left: 50px">
                很抱歉，我们目前没有开通这趟车次，请尝试选择其他车次，祝您旅途愉快！
            </p>
        </div>

        <!--按照价格排序-->
        <div class="search_result_by_price" id="result_by_price">
            {% for railway in usable_railways_by_price %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="railway_name">{{ railway.name }}</p> {# 单行居中 #}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# 多行居中 #}
                                <span style="font-size: xx-large">{{ railway.leave_time }}</span>
                                <br>
                                {{ railway.leave_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ railway.arrive_time }}</span>
                                <br>
                                {{ railway.arrive_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">满座率</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ railway.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ railway.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' railway.id %}"
                                   class="btn btn-sm btn-warning">订票</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!--按照出发时间排序-->
        <div class="search_result_by_ltime" id="result_by_ltime" style="display: none">
            {% for railway in usable_railways_by_ltime %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="railway_name">{{ railway.name }}</p> {# 单行居中#}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# 多行居中 #}
                                <span style="font-size: xx-large">{{ railway.leave_time }}</span>
                                <br>
                                {{ railway.leave_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ railway.arrive_time }}</span>
                                <br>
                                {{ railway.arrive_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">满座率</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ railway.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ railway.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' railway.id %}"
                                   class="btn btn-sm btn-warning">订票</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!--按照到达时间排序-->
        <div class="search_result_by_atime" id="result_by_atime" style="display: none">
            {% for railway in usable_railways_by_atime %}
                <div class="one_line">
                    <div class="col-sm-12">
                        <div class="col-sm-3">
                            <p class="railway_name">{{ railway.name }}</p> {# 单行居中 #}
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px"> {# 多行居中 #}
                                <span style="font-size: xx-large">{{ railway.leave_time }}</span>
                                <br>
                                {{ railway.leave_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 10px">
                                <span style="font-size: xx-large">{{ railway.arrive_time }}</span>
                                <br>
                                {{ railway.arrive_station }}
                            </p>
                        </div>
                        <div class="col-sm-3">
                            <p style="padding: 22px 0;">
                                <span style="position:absolute;margin-top: 10px;margin-left: -50px;
                                    font-size:smaller;color: gray;">满座率</span>
                                <span style="position:absolute;margin-top: 26px;margin-left: -47px;
                                    font-size:smaller;color: gray">{{ railway.book_sum }}/100</span>
                                <sup>￥</sup>
                                <span style="color: #ff6600;font-size: xx-large;">{{ railway.price }}</span>
                                <sub>起</sub>&nbsp;
                                <a href="{% url 'booksystem:book_ticket' railway.id %}"
                                   class="btn btn-sm btn-warning">订票</a>
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}